
# Enhanced products list - 50+ Indian products
products = [
    # Electronics - Smartphones (ID: 1-10)
    {
        "id": 1,
        "name": "iPhone 15 Pro Max (1 TB) - Blue Titanium",
        "price": 189900,
        "original_price": 199900,
        "discount": 5,
        "category": "electronics",
        "subcategory": "smartphones",
        "rating": 4.9,
        "reviews": 24567,
        "image": "https://images.unsplash.com/photo-1695048133142-1a20484d2569?w=500",
        "badge": "New Launch",
        "delivery": "Free Delivery by Tomorrow",
        "prime": True,
        "assured": True,
        "bank_offers": ["10% off on HDFC Cards", "No Cost EMI"],
        "colors": ["Blue", "Black", "White"],
        "in_stock": True
    },
    {
        "id": 2,
        "name": "Samsung Galaxy S24 Ultra (1 TB) - Titanium Gray",
        "price": 164999,
        "original_price": 174999,
        "discount": 6,
        "category": "electronics",
        "subcategory": "smartphones",
        "rating": 4.8,
        "reviews": 18934,
        "image": "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500",
        "badge": "Bestseller",
        "delivery": "Free Delivery by Tomorrow",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹5000 off on HDFC", "Exchange Bonus"],
        "colors": ["Gray", "Black", "Violet"],
        "in_stock": True
    },
    {
        "id": 3,
        "name": "OnePlus 12 (16GB RAM, 512GB) - Flowy Emerald",
        "price": 69999,
        "original_price": 75999,
        "discount": 8,
        "category": "electronics",
        "subcategory": "smartphones",
        "rating": 4.7,
        "reviews": 34567,
        "image": "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500",
        "badge": "Popular",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹3000 off on ICICI", "No Cost EMI"],
        "colors": ["Emerald", "Black"],
        "in_stock": True
    },
    {
        "id": 4,
        "name": "Nothing Phone (2) 12GB RAM - Dark Gray",
        "price": 44999,
        "original_price": 49999,
        "discount": 10,
        "category": "electronics",
        "subcategory": "smartphones",
        "rating": 4.6,
        "reviews": 12345,
        "image": "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500",
        "badge": "10% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹2000 off on SBI"],
        "colors": ["Gray", "White"],
        "in_stock": True
    },
    {
        "id": 5,
        "name": "Vivo X100 Pro (16GB RAM) - Asteroid Black",
        "price": 89999,
        "original_price": 99999,
        "discount": 10,
        "category": "electronics",
        "subcategory": "smartphones",
        "rating": 4.5,
        "reviews": 8765,
        "image": "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500",
        "badge": "New",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹4000 off on HDFC"],
        "colors": ["Black", "Silver"],
        "in_stock": True
    },
    {
        "id": 6,
        "name": "Xiaomi 14 Pro (12GB RAM) - White",
        "price": 79999,
        "original_price": 89999,
        "discount": 11,
        "category": "electronics",
        "subcategory": "smartphones",
        "rating": 4.4,
        "reviews": 6543,
        "image": "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500",
        "badge": "11% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹3500 off on ICICI"],
        "colors": ["White", "Black"],
        "in_stock": True
    },
    {
        "id": 7,
        "name": "Motorola Edge 50 Pro - Black",
        "price": 39999,
        "original_price": 45999,
        "discount": 13,
        "category": "electronics",
        "subcategory": "smartphones",
        "rating": 4.5,
        "reviews": 4321,
        "image": "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500",
        "badge": "13% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹1500 off on SBI"],
        "colors": ["Black", "Blue"],
        "in_stock": True
    },
    {
        "id": 8,
        "name": "Realme GT 5G (12GB RAM) - Silver",
        "price": 42999,
        "original_price": 47999,
        "discount": 10,
        "category": "electronics",
        "subcategory": "smartphones",
        "rating": 4.4,
        "reviews": 9876,
        "image": "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500",
        "badge": "10% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹2000 off on HDFC"],
        "colors": ["Silver", "Black"],
        "in_stock": True
    },
    {
        "id": 9,
        "name": "iQOO 12 (16GB RAM) - Legend",
        "price": 52999,
        "original_price": 58999,
        "discount": 10,
        "category": "electronics",
        "subcategory": "smartphones",
        "rating": 4.6,
        "reviews": 5678,
        "image": "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500",
        "badge": "10% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹2500 off on ICICI"],
        "colors": ["White", "Black"],
        "in_stock": True
    },
    {
        "id": 10,
        "name": "Google Pixel 8 Pro (256GB) - Bay Blue",
        "price": 106999,
        "original_price": 119999,
        "discount": 11,
        "category": "electronics",
        "subcategory": "smartphones",
        "rating": 4.7,
        "reviews": 7890,
        "image": "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=500",
        "badge": "11% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹5000 off on HDFC"],
        "colors": ["Bay Blue", "Obsidian"],
        "in_stock": True
    },
    
    # Electronics - Laptops (ID: 11-20)
    {
        "id": 11,
        "name": "Apple MacBook Pro 16 (M3 Max) - Space Black",
        "price": 399999,
        "original_price": 429999,
        "discount": 7,
        "category": "electronics",
        "subcategory": "laptops",
        "rating": 4.9,
        "reviews": 3456,
        "image": "https://images.unsplash.com/photo-1517336714731-489689fd1ca4?w=500",
        "badge": "New Launch",
        "delivery": "Free Delivery by Tomorrow",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹15000 off on HDFC", "No Cost EMI"],
        "config": ["M3 Max", "48GB RAM", "1TB SSD"],
        "in_stock": True
    },
    {
        "id": 12,
        "name": "ASUS ROG Zephyrus G16 (2024) - Eclipse Gray",
        "price": 249990,
        "original_price": 269990,
        "discount": 7,
        "category": "electronics",
        "subcategory": "laptops",
        "rating": 4.8,
        "reviews": 2345,
        "image": "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500",
        "badge": "Gaming Beast",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹10000 off on ICICI"],
        "config": ["Intel i9", "32GB RAM", "1TB SSD", "RTX 4080"],
        "in_stock": True
    },
    {
        "id": 13,
        "name": "Dell XPS 15 (9530) - Platinum Silver",
        "price": 289990,
        "original_price": 299990,
        "discount": 3,
        "category": "electronics",
        "subcategory": "laptops",
        "rating": 4.7,
        "reviews": 1234,
        "image": "https://images.unsplash.com/photo-1593642632823-8f785ba67e45?w=500",
        "badge": "Premium",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹12000 off on HDFC"],
        "config": ["Intel i9", "32GB RAM", "1TB SSD", "OLED"],
        "in_stock": True
    },
    {
        "id": 14,
        "name": "HP Spectre x360 (14-inch) - Nightfall Black",
        "price": 179990,
        "original_price": 199990,
        "discount": 10,
        "category": "electronics",
        "subcategory": "laptops",
        "rating": 4.6,
        "reviews": 3456,
        "image": "https://images.unsplash.com/photo-1544731612-de7f96afe55f?w=500",
        "badge": "10% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹8000 off on SBI"],
        "config": ["Intel i7", "16GB RAM", "1TB SSD", "Touch"],
        "in_stock": True
    },
    {
        "id": 15,
        "name": "Lenovo Legion 9i - Storm Grey",
        "price": 329990,
        "original_price": 349990,
        "discount": 6,
        "category": "electronics",
        "subcategory": "laptops",
        "rating": 4.8,
        "reviews": 890,
        "image": "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500",
        "badge": "Limited Edition",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹15000 off on HDFC"],
        "config": ["Intel i9", "64GB RAM", "2TB SSD", "RTX 4090"],
        "in_stock": True
    },
    {
        "id": 16,
        "name": "Microsoft Surface Laptop 5 - Platinum",
        "price": 114990,
        "original_price": 129990,
        "discount": 12,
        "category": "electronics",
        "subcategory": "laptops",
        "rating": 4.5,
        "reviews": 5678,
        "image": "https://images.unsplash.com/photo-1611186871348-b1ce696e52c9?w=500",
        "badge": "12% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹5000 off on ICICI"],
        "config": ["Intel i7", "16GB RAM", "512GB SSD"],
        "in_stock": True
    },
    {
        "id": 17,
        "name": "Acer Predator Helios 18 - Abyssal Black",
        "price": 279990,
        "original_price": 299990,
        "discount": 7,
        "category": "electronics",
        "subcategory": "laptops",
        "rating": 4.7,
        "reviews": 2341,
        "image": "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500",
        "badge": "Gaming",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹10000 off on HDFC"],
        "config": ["Intel i9", "32GB RAM", "1TB SSD", "RTX 4080"],
        "in_stock": True
    },
    {
        "id": 18,
        "name": "MSI Raider GE78 HX - Core Black",
        "price": 299990,
        "original_price": 329990,
        "discount": 9,
        "category": "electronics",
        "subcategory": "laptops",
        "rating": 4.8,
        "reviews": 1456,
        "image": "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500",
        "badge": "9% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹12000 off on ICICI"],
        "config": ["Intel i9", "64GB RAM", "2TB SSD", "RTX 4090"],
        "in_stock": True
    },
    {
        "id": 19,
        "name": "Gigabyte Aorus 17X - Black",
        "price": 289990,
        "original_price": 309990,
        "discount": 6,
        "category": "electronics",
        "subcategory": "laptops",
        "rating": 4.6,
        "reviews": 987,
        "image": "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500",
        "badge": "6% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹11000 off on HDFC"],
        "config": ["Intel i9", "32GB RAM", "1TB SSD", "RTX 4080"],
        "in_stock": True
    },
    {
        "id": 20,
        "name": "Razer Blade 16 - Mercury White",
        "price": 359990,
        "original_price": 379990,
        "discount": 5,
        "category": "electronics",
        "subcategory": "laptops",
        "rating": 4.9,
        "reviews": 2345,
        "image": "https://images.unsplash.com/photo-1603302576837-37561b2e2302?w=500",
        "badge": "Premium",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹15000 off on ICICI"],
        "config": ["Intel i9", "64GB RAM", "2TB SSD", "RTX 4090"],
        "in_stock": True
    },
    
    # Electronics - Audio (ID: 21-30)
    {
        "id": 21,
        "name": "Sony WH-1000XM5 - Silver",
        "price": 29990,
        "original_price": 34990,
        "discount": 14,
        "category": "electronics",
        "subcategory": "audio",
        "rating": 4.8,
        "reviews": 45678,
        "image": "https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=500",
        "badge": "Bestseller",
        "delivery": "Free Delivery by Tomorrow",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹2000 off on HDFC"],
        "in_stock": True
    },
    {
        "id": 22,
        "name": "Apple AirPods Pro (2nd Gen) - White",
        "price": 24900,
        "original_price": 26900,
        "discount": 7,
        "category": "electronics",
        "subcategory": "audio",
        "rating": 4.9,
        "reviews": 98765,
        "image": "https://images.unsplash.com/photo-1588423771073-b8903fbb85b5?w=500",
        "badge": "Top Rated",
        "delivery": "Free Delivery by Tomorrow",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹1000 off on ICICI"],
        "in_stock": True
    },
    {
        "id": 23,
        "name": "boAt Nirvana 751 ANC - Black",
        "price": 3999,
        "original_price": 7999,
        "discount": 50,
        "category": "electronics",
        "subcategory": "audio",
        "rating": 4.3,
        "reviews": 123456,
        "image": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["10% off on HDFC"],
        "in_stock": True
    },
    {
        "id": 24,
        "name": "JBL Flip 6 - Black",
        "price": 10999,
        "original_price": 13999,
        "discount": 21,
        "category": "electronics",
        "subcategory": "audio",
        "rating": 4.6,
        "reviews": 23456,
        "image": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=500",
        "badge": "21% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹1000 off on SBI"],
        "in_stock": True
    },
    {
        "id": 25,
        "name": "Marshall Stanmore II - Black",
        "price": 34999,
        "original_price": 39999,
        "discount": 13,
        "category": "electronics",
        "subcategory": "audio",
        "rating": 4.7,
        "reviews": 12345,
        "image": "https://images.unsplash.com/photo-1563330232-57114bb0823c?w=500",
        "badge": "13% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹2000 off on HDFC"],
        "in_stock": True
    },
    {
        "id": 26,
        "name": "Sennheiser Momentum 4 - Black",
        "price": 34990,
        "original_price": 39990,
        "discount": 13,
        "category": "electronics",
        "subcategory": "audio",
        "rating": 4.7,
        "reviews": 8765,
        "image": "https://images.unsplash.com/photo-1487215078519-e21cc028cb29?w=500",
        "badge": "Premium",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹2000 off on ICICI"],
        "in_stock": True
    },
    {
        "id": 27,
        "name": "Bose QuietComfort Ultra - Black",
        "price": 39900,
        "original_price": 44900,
        "discount": 11,
        "category": "electronics",
        "subcategory": "audio",
        "rating": 4.8,
        "reviews": 6543,
        "image": "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=500",
        "badge": "11% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹2500 off on HDFC"],
        "in_stock": True
    },
    {
        "id": 28,
        "name": "Audio-Technica ATH-M50x - Black",
        "price": 13999,
        "original_price": 16999,
        "discount": 18,
        "category": "electronics",
        "subcategory": "audio",
        "rating": 4.8,
        "reviews": 34567,
        "image": "https://images.unsplash.com/photo-1484704849700-f032a568e944?w=500",
        "badge": "18% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹1000 off on SBI"],
        "in_stock": True
    },
    {
        "id": 29,
        "name": "Jabra Elite 10 - Black",
        "price": 19999,
        "original_price": 22999,
        "discount": 13,
        "category": "electronics",
        "subcategory": "audio",
        "rating": 4.5,
        "reviews": 4321,
        "image": "https://images.unsplash.com/photo-1606220838315-056192d5e927?w=500",
        "badge": "13% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹1500 off on ICICI"],
        "in_stock": True
    },
    {
        "id": 30,
        "name": "Samsung Galaxy Buds2 Pro - Graphite",
        "price": 15999,
        "original_price": 19999,
        "discount": 20,
        "category": "electronics",
        "subcategory": "audio",
        "rating": 4.6,
        "reviews": 23456,
        "image": "https://images.unsplash.com/photo-1572569511254-d8f925fe2cbb?w=500",
        "badge": "20% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "bank_offers": ["₹1500 off on HDFC"],
        "in_stock": True
    },
    
    # Fashion - Men's Clothing (ID: 31-40)
    {
        "id": 31,
        "name": "US Polo Association Men's T-shirt - Navy Blue",
        "price": 899,
        "original_price": 1999,
        "discount": 55,
        "category": "fashion",
        "subcategory": "mens_clothing",
        "rating": 4.4,
        "reviews": 23456,
        "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500",
        "badge": "55% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "in_stock": True
    },
    {
        "id": 32,
        "name": "Levi's Men's 512 Slim Fit Jeans - Blue",
        "price": 2199,
        "original_price": 3999,
        "discount": 45,
        "category": "fashion",
        "subcategory": "mens_clothing",
        "rating": 4.5,
        "reviews": 18765,
        "image": "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500",
        "badge": "45% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": ["28", "30", "32", "34", "36"],
        "in_stock": True
    },
    {
        "id": 33,
        "name": "Peter England Men's Formal Shirt - White",
        "price": 1299,
        "original_price": 2499,
        "discount": 48,
        "category": "fashion",
        "subcategory": "mens_clothing",
        "rating": 4.3,
        "reviews": 34567,
        "image": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500",
        "badge": "48% Off",
        "delivery": "₹40 Delivery",
        "prime": False,
        "assured": True,
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "in_stock": True
    },
    {
        "id": 34,
        "name": "Van Heusen Men's Blazer - Navy",
        "price": 4999,
        "original_price": 9999,
        "discount": 50,
        "category": "fashion",
        "subcategory": "mens_clothing",
        "rating": 4.6,
        "reviews": 5678,
        "image": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": ["S", "M", "L", "XL"],
        "in_stock": True
    },
    {
        "id": 35,
        "name": "Allen Solly Men's Sweater - Grey",
        "price": 1799,
        "original_price": 3499,
        "discount": 49,
        "category": "fashion",
        "subcategory": "mens_clothing",
        "rating": 4.4,
        "reviews": 12345,
        "image": "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=500",
        "badge": "49% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": ["S", "M", "L", "XL"],
        "in_stock": True
    },
    {
        "id": 36,
        "name": "Louis Philippe Men's Suit - Charcoal",
        "price": 12999,
        "original_price": 24999,
        "discount": 48,
        "category": "fashion",
        "subcategory": "mens_clothing",
        "rating": 4.7,
        "reviews": 2345,
        "image": "https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=500",
        "badge": "48% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": ["38", "40", "42", "44"],
        "in_stock": True
    },
    {
        "id": 37,
        "name": "Jack & Jones Men's Jacket - Black",
        "price": 2999,
        "original_price": 5999,
        "discount": 50,
        "category": "fashion",
        "subcategory": "mens_clothing",
        "rating": 4.5,
        "reviews": 8765,
        "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": ["S", "M", "L", "XL"],
        "in_stock": True
    },
    {
        "id": 38,
        "name": "Flying Machine Men's Joggers - Grey",
        "price": 1499,
        "original_price": 2999,
        "discount": 50,
        "category": "fashion",
        "subcategory": "mens_clothing",
        "rating": 4.3,
        "reviews": 23456,
        "image": "https://images.unsplash.com/photo-1556905055-8f358a7a47b2?w=500",
        "badge": "50% Off",
        "delivery": "₹40 Delivery",
        "prime": False,
        "assured": True,
        "sizes": ["S", "M", "L", "XL"],
        "in_stock": True
    },
    {
        "id": 39,
        "name": "Indian Terrain Men's Polo - Green",
        "price": 1099,
        "original_price": 2199,
        "discount": 50,
        "category": "fashion",
        "subcategory": "mens_clothing",
        "rating": 4.4,
        "reviews": 9876,
        "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": ["S", "M", "L", "XL"],
        "in_stock": True
    },
    {
        "id": 40,
        "name": "Park Avenue Men's Kurta - White",
        "price": 1499,
        "original_price": 2999,
        "discount": 50,
        "category": "fashion",
        "subcategory": "mens_clothing",
        "rating": 4.5,
        "reviews": 5678,
        "image": "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": ["S", "M", "L", "XL", "XXL"],
        "in_stock": True
    },
    
    # Fashion - Women's Clothing (ID: 41-50)
    {
        "id": 41,
        "name": "Biba Women's Kurta Set - Pink",
        "price": 1999,
        "original_price": 3999,
        "discount": 50,
        "category": "fashion",
        "subcategory": "womens_clothing",
        "rating": 4.6,
        "reviews": 34567,
        "image": "https://images.unsplash.com/photo-1618354691373-d851c5c3a990?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": ["S", "M", "L", "XL"],
        "in_stock": True
    },
    {
        "id": 42,
        "name": "Libas Women's Dress - Blue",
        "price": 2499,
        "original_price": 4999,
        "discount": 50,
        "category": "fashion",
        "subcategory": "womens_clothing",
        "rating": 4.5,
        "reviews": 23456,
        "image": "https://images.unsplash.com/photo-1612336307429-8a898d10e223?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": ["S", "M", "L", "XL"],
        "in_stock": True
    },
    {
        "id": 43,
        "name": "W for Women Jeans - Light Blue",
        "price": 1799,
        "original_price": 3599,
        "discount": 50,
        "category": "fashion",
        "subcategory": "womens_clothing",
        "rating": 4.4,
        "reviews": 18765,
        "image": "https://images.unsplash.com/photo-1541099649105-f69ad21f3246?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": ["26", "28", "30", "32", "34"],
        "in_stock": True
    },
    {
        "id": 44,
        "name": "H&M Women's Top - Black",
        "price": 999,
        "original_price": 1999,
        "discount": 50,
        "category": "fashion",
        "subcategory": "womens_clothing",
        "rating": 4.3,
        "reviews": 34567,
        "image": "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500",
        "badge": "50% Off",
        "delivery": "₹40 Delivery",
        "prime": False,
        "assured": True,
        "sizes": ["S", "M", "L", "XL"],
        "in_stock": True
    },
    {
        "id": 45,
        "name": "FabIndia Women's Saree - Red",
        "price": 4999,
        "original_price": 9999,
        "discount": 50,
        "category": "fashion",
        "subcategory": "womens_clothing",
        "rating": 4.8,
        "reviews": 8765,
        "image": "https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": ["Free Size"],
        "in_stock": True
    },
    {
        "id": 46,
        "name": "Van Heusen Women's Blazer - Navy",
        "price": 5999,
        "original_price": 11999,
        "discount": 50,
        "category": "fashion",
        "subcategory": "womens_clothing",
        "rating": 4.6,
        "reviews": 3456,
        "image": "https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": ["S", "M", "L", "XL"],
        "in_stock": True
    },
    {
        "id": 47,
        "name": "Allen Solly Women's Shirt - White",
        "price": 1499,
        "original_price": 2999,
        "discount": 50,
        "category": "fashion",
        "subcategory": "womens_clothing",
        "rating": 4.4,
        "reviews": 12345,
        "image": "https://images.unsplash.com/photo-1596755094514-f87e34085b2c?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": ["S", "M", "L", "XL"],
        "in_stock": True
    },
    {
        "id": 48,
        "name": "Max Women's Leggings - Black",
        "price": 499,
        "original_price": 999,
        "discount": 50,
        "category": "fashion",
        "subcategory": "womens_clothing",
        "rating": 4.2,
        "reviews": 56789,
        "image": "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=500",
        "badge": "50% Off",
        "delivery": "₹30 Delivery",
        "prime": False,
        "assured": True,
        "sizes": ["S", "M", "L", "XL"],
        "in_stock": True
    },
    {
        "id": 49,
        "name": "Zara Women's Jacket - Brown",
        "price": 3999,
        "original_price": 7999,
        "discount": 50,
        "category": "fashion",
        "subcategory": "womens_clothing",
        "rating": 4.5,
        "reviews": 5678,
        "image": "https://images.unsplash.com/photo-1551028719-00167b16eac5?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": ["S", "M", "L"],
        "in_stock": True
    },
    {
        "id": 50,
        "name": "Forever 21 Women's Skirt - Black",
        "price": 1499,
        "original_price": 2999,
        "discount": 50,
        "category": "fashion",
        "subcategory": "womens_clothing",
        "rating": 4.3,
        "reviews": 9876,
        "image": "https://images.unsplash.com/photo-1583496661160-fb5886a0aaaa?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": ["S", "M", "L"],
        "in_stock": True
    },
    
    # Footwear (ID: 51-60)
    {
        "id": 51,
        "name": "Nike Air Max 270 - Black/White",
        "price": 12995,
        "original_price": 16995,
        "discount": 24,
        "category": "footwear",
        "subcategory": "sports_shoes",
        "rating": 4.6,
        "reviews": 34567,
        "image": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500",
        "badge": "24% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": [7,8,9,10,11],
        "in_stock": True
    },
    {
        "id": 52,
        "name": "Adidas Ultraboost 22 - Core Black",
        "price": 15999,
        "original_price": 19999,
        "discount": 20,
        "category": "footwear",
        "subcategory": "sports_shoes",
        "rating": 4.7,
        "reviews": 23456,
        "image": "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=500",
        "badge": "20% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": [7,8,9,10,11,12],
        "in_stock": True
    },
    {
        "id": 53,
        "name": "Puma RS-X3 - White/Red",
        "price": 8999,
        "original_price": 11999,
        "discount": 25,
        "category": "footwear",
        "subcategory": "casual_shoes",
        "rating": 4.5,
        "reviews": 18765,
        "image": "https://images.unsplash.com/photo-1608231387042-66d1773070a5?w=500",
        "badge": "25% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": [7,8,9,10,11],
        "in_stock": True
    },
    {
        "id": 54,
        "name": "Woodland Men's Boots - Brown",
        "price": 4999,
        "original_price": 7999,
        "discount": 38,
        "category": "footwear",
        "subcategory": "boots",
        "rating": 4.6,
        "reviews": 12345,
        "image": "https://images.unsplash.com/photo-1520639888713-7851133b1ed0?w=500",
        "badge": "38% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": [7,8,9,10,11],
        "in_stock": True
    },
    {
        "id": 55,
        "name": "Bata Women's Heels - Black",
        "price": 1999,
        "original_price": 3999,
        "discount": 50,
        "category": "footwear",
        "subcategory": "heels",
        "rating": 4.3,
        "reviews": 23456,
        "image": "https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": [5,6,7,8,9],
        "in_stock": True
    },
    {
        "id": 56,
        "name": "Clarks Men's Formal Shoes - Brown",
        "price": 4999,
        "original_price": 8999,
        "discount": 44,
        "category": "footwear",
        "subcategory": "formal_shoes",
        "rating": 4.5,
        "reviews": 8765,
        "image": "https://images.unsplash.com/photo-1614252369475-531eba835eb1?w=500",
        "badge": "44% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": [7,8,9,10,11],
        "in_stock": True
    },
    {
        "id": 57,
        "name": "Crocs Unisex Clogs - Navy",
        "price": 2499,
        "original_price": 3999,
        "discount": 38,
        "category": "footwear",
        "subcategory": "casual",
        "rating": 4.5,
        "reviews": 56789,
        "image": "https://images.unsplash.com/photo-1605733160314-4fc7dac4bb16?w=500",
        "badge": "38% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": [6,7,8,9,10,11],
        "in_stock": True
    },
    {
        "id": 58,
        "name": "Reebok Women's Sneakers - White",
        "price": 3999,
        "original_price": 6999,
        "discount": 43,
        "category": "footwear",
        "subcategory": "sneakers",
        "rating": 4.4,
        "reviews": 12345,
        "image": "https://images.unsplash.com/photo-1595950653106-6c9ebd614d3a?w=500",
        "badge": "43% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": [5,6,7,8,9],
        "in_stock": True
    },
    {
        "id": 59,
        "name": "Skechers Men's Slip-ins - Black",
        "price": 5999,
        "original_price": 7999,
        "discount": 25,
        "category": "footwear",
        "subcategory": "casual",
        "rating": 4.5,
        "reviews": 34567,
        "image": "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=500",
        "badge": "25% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "sizes": [7,8,9,10,11,12],
        "in_stock": True
    },
    {
        "id": 60,
        "name": "Liberty Men's Sandals - Brown",
        "price": 999,
        "original_price": 1999,
        "discount": 50,
        "category": "footwear",
        "subcategory": "sandals",
        "rating": 4.2,
        "reviews": 45678,
        "image": "https://images.unsplash.com/photo-1549298916-b41d501d3772?w=500",
        "badge": "50% Off",
        "delivery": "₹30 Delivery",
        "prime": False,
        "assured": True,
        "sizes": [7,8,9,10,11],
        "in_stock": True
    },
    
    # Home & Kitchen (ID: 61-70)
    {
        "id": 61,
        "name": "Prestige Svachh Induction Cooktop",
        "price": 3499,
        "original_price": 5999,
        "discount": 42,
        "category": "home",
        "subcategory": "kitchen_appliances",
        "rating": 4.5,
        "reviews": 23456,
        "image": "https://images.unsplash.com/photo-1584990347449-a7a6cf28f4e7?w=500",
        "badge": "42% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 62,
        "name": "Bajaj DX-6 1000W Dry Iron",
        "price": 799,
        "original_price": 1495,
        "discount": 47,
        "category": "home",
        "subcategory": "home_appliances",
        "rating": 4.4,
        "reviews": 56789,
        "image": "https://images.unsplash.com/photo-1584990347449-a7a6cf28f4e7?w=500",
        "badge": "47% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 63,
        "name": "Sleepwell Proffesional Mattress",
        "price": 8999,
        "original_price": 14999,
        "discount": 40,
        "category": "home",
        "subcategory": "furniture",
        "rating": 4.6,
        "reviews": 12345,
        "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500",
        "badge": "40% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 64,
        "name": "Philips Air Purifier AC2887/20",
        "price": 18999,
        "original_price": 24999,
        "discount": 24,
        "category": "home",
        "subcategory": "air_purifiers",
        "rating": 4.7,
        "reviews": 5678,
        "image": "https://images.unsplash.com/photo-1585776245863-b92d6e86e8da?w=500",
        "badge": "24% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 65,
        "name": "Havells 1200mm Ceiling Fan - Brown",
        "price": 2499,
        "original_price": 3999,
        "discount": 38,
        "category": "home",
        "subcategory": "fans",
        "rating": 4.5,
        "reviews": 34567,
        "image": "https://images.unsplash.com/photo-1584990347449-a7a6cf28f4e7?w=500",
        "badge": "38% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 66,
        "name": "Milton Thermosteel Water Bottle - 1L",
        "price": 599,
        "original_price": 999,
        "discount": 40,
        "category": "home",
        "subcategory": "kitchen",
        "rating": 4.4,
        "reviews": 45678,
        "image": "https://images.unsplash.com/photo-1584990347449-a7a6cf28f4e7?w=500",
        "badge": "40% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 67,
        "name": "Godrej Eon Refrigerator 240L",
        "price": 18999,
        "original_price": 24999,
        "discount": 24,
        "category": "home",
        "subcategory": "refrigerators",
        "rating": 4.5,
        "reviews": 23456,
        "image": "https://images.unsplash.com/photo-1584990347449-a7a6cf28f4e7?w=500",
        "badge": "24% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 68,
        "name": "LG 6.5kg Fully Automatic Washing Machine",
        "price": 14999,
        "original_price": 19999,
        "discount": 25,
        "category": "home",
        "subcategory": "washing_machines",
        "rating": 4.6,
        "reviews": 34567,
        "image": "https://images.unsplash.com/photo-1584990347449-a7a6cf28f4e7?w=500",
        "badge": "25% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 69,
        "name": "Butterfly Rapid 4 Burner Gas Stove",
        "price": 4499,
        "original_price": 6999,
        "discount": 36,
        "category": "home",
        "subcategory": "kitchen_appliances",
        "rating": 4.5,
        "reviews": 12345,
        "image": "https://images.unsplash.com/photo-1584990347449-a7a6cf28f4e7?w=500",
        "badge": "36% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 70,
        "name": "Wakefit 10\" Orthopedic Memory Foam Mattress",
        "price": 12999,
        "original_price": 19999,
        "discount": 35,
        "category": "home",
        "subcategory": "furniture",
        "rating": 4.7,
        "reviews": 45678,
        "image": "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=500",
        "badge": "35% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    
    # Books (ID: 71-80)
    {
        "id": 71,
        "name": "Rich Dad Poor Dad - Robert Kiyosaki",
        "price": 299,
        "original_price": 499,
        "discount": 40,
        "category": "books",
        "subcategory": "finance",
        "rating": 4.8,
        "reviews": 234567,
        "image": "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500",
        "badge": "Bestseller",
        "delivery": "₹30 Delivery",
        "prime": False,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 72,
        "name": "Atomic Habits - James Clear",
        "price": 399,
        "original_price": 599,
        "discount": 33,
        "category": "books",
        "subcategory": "self_help",
        "rating": 4.9,
        "reviews": 345678,
        "image": "https://images.unsplash.com/photo-1544716278-e513176f20b5?w=500",
        "badge": "33% Off",
        "delivery": "₹30 Delivery",
        "prime": False,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 73,
        "name": "The Psychology of Money - Morgan Housel",
        "price": 349,
        "original_price": 599,
        "discount": 42,
        "category": "books",
        "subcategory": "finance",
        "rating": 4.8,
        "reviews": 187654,
        "image": "https://images.unsplash.com/photo-1544716278-e513176f20b5?w=500",
        "badge": "42% Off",
        "delivery": "₹30 Delivery",
        "prime": False,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 74,
        "name": "Wings of Fire - APJ Abdul Kalam",
        "price": 249,
        "original_price": 399,
        "discount": 38,
        "category": "books",
        "subcategory": "biography",
        "rating": 4.9,
        "reviews": 456789,
        "image": "https://images.unsplash.com/photo-1544716278-e513176f20b5?w=500",
        "badge": "38% Off",
        "delivery": "₹30 Delivery",
        "prime": False,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 75,
        "name": "The Alchemist - Paulo Coelho",
        "price": 299,
        "original_price": 499,
        "discount": 40,
        "category": "books",
        "subcategory": "fiction",
        "rating": 4.7,
        "reviews": 345678,
        "image": "https://images.unsplash.com/photo-1544716278-e513176f20b5?w=500",
        "badge": "40% Off",
        "delivery": "₹30 Delivery",
        "prime": False,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 76,
        "name": "Think and Grow Rich - Napoleon Hill",
        "price": 199,
        "original_price": 399,
        "discount": 50,
        "category": "books",
        "subcategory": "self_help",
        "rating": 4.7,
        "reviews": 234567,
        "image": "https://images.unsplash.com/photo-1544716278-e513176f20b5?w=500",
        "badge": "50% Off",
        "delivery": "₹30 Delivery",
        "prime": False,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 77,
        "name": "Ikigai - The Japanese Secret",
        "price": 399,
        "original_price": 599,
        "discount": 33,
        "category": "books",
        "subcategory": "self_help",
        "rating": 4.6,
        "reviews": 345678,
        "image": "https://images.unsplash.com/photo-1544716278-e513176f20b5?w=500",
        "badge": "33% Off",
        "delivery": "₹30 Delivery",
        "prime": False,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 78,
        "name": "The Power of Your Subconscious Mind",
        "price": 249,
        "original_price": 399,
        "discount": 38,
        "category": "books",
        "subcategory": "self_help",
        "rating": 4.6,
        "reviews": 123456,
        "image": "https://images.unsplash.com/photo-1544716278-e513176f20b5?w=500",
        "badge": "38% Off",
        "delivery": "₹30 Delivery",
        "prime": False,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 79,
        "name": "Sapiens - Yuval Noah Harari",
        "price": 599,
        "original_price": 999,
        "discount": 40,
        "category": "books",
        "subcategory": "history",
        "rating": 4.8,
        "reviews": 234567,
        "image": "https://images.unsplash.com/photo-1544716278-e513176f20b5?w=500",
        "badge": "40% Off",
        "delivery": "₹30 Delivery",
        "prime": False,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 80,
        "name": "The Subtle Art of Not Giving a F*ck",
        "price": 399,
        "original_price": 599,
        "discount": 33,
        "category": "books",
        "subcategory": "self_help",
        "rating": 4.5,
        "reviews": 456789,
        "image": "https://images.unsplash.com/photo-1544716278-e513176f20b5?w=500",
        "badge": "33% Off",
        "delivery": "₹30 Delivery",
        "prime": False,
        "assured": True,
        "in_stock": True
    },
    
    # Sports & Fitness (ID: 81-90)
    {
        "id": 81,
        "name": "Yonex Voltric 7DG Badminton Racket",
        "price": 2999,
        "original_price": 3999,
        "discount": 25,
        "category": "sports",
        "subcategory": "badminton",
        "rating": 4.6,
        "reviews": 23456,
        "image": "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=500",
        "badge": "25% Off",
        "delivery": "₹40 Delivery",
        "prime": False,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 82,
        "name": "Cosco 5kg PVC Dumbbells Set",
        "price": 1499,
        "original_price": 2999,
        "discount": 50,
        "category": "sports",
        "subcategory": "fitness",
        "rating": 4.4,
        "reviews": 56789,
        "image": "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 83,
        "name": "Nike Premier League Football - Size 5",
        "price": 2499,
        "original_price": 3499,
        "discount": 29,
        "category": "sports",
        "subcategory": "football",
        "rating": 4.5,
        "reviews": 34567,
        "image": "https://images.unsplash.com/photo-1614632537423-0e6eec9b0b9a?w=500",
        "badge": "29% Off",
        "delivery": "₹40 Delivery",
        "prime": False,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 84,
        "name": "SG Test Cricket Bat - English Willow",
        "price": 5999,
        "original_price": 9999,
        "discount": 40,
        "category": "sports",
        "subcategory": "cricket",
        "rating": 4.7,
        "reviews": 12345,
        "image": "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=500",
        "badge": "40% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 85,
        "name": "PTM 6ft Foldable Table Tennis Table",
        "price": 12999,
        "original_price": 19999,
        "discount": 35,
        "category": "sports",
        "subcategory": "table_tennis",
        "rating": 4.5,
        "reviews": 3456,
        "image": "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=500",
        "badge": "35% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 86,
        "name": "Yamaha 3x Badminton Shuttlecock",
        "price": 699,
        "original_price": 999,
        "discount": 30,
        "category": "sports",
        "subcategory": "badminton",
        "rating": 4.4,
        "reviews": 23456,
        "image": "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=500",
        "badge": "30% Off",
        "delivery": "₹30 Delivery",
        "prime": False,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 87,
        "name": "Boldfit Yoga Mat - 6mm Thick",
        "price": 499,
        "original_price": 999,
        "discount": 50,
        "category": "sports",
        "subcategory": "yoga",
        "rating": 4.5,
        "reviews": 345678,
        "image": "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 88,
        "name": "Cockatoo Pro Skipping Rope",
        "price": 299,
        "original_price": 599,
        "discount": 50,
        "category": "sports",
        "subcategory": "fitness",
        "rating": 4.3,
        "reviews": 123456,
        "image": "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 89,
        "name": "Lifelong 3HP Treadmill",
        "price": 24999,
        "original_price": 39999,
        "discount": 38,
        "category": "sports",
        "subcategory": "fitness",
        "rating": 4.4,
        "reviews": 5678,
        "image": "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500",
        "badge": "38% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 90,
        "name": "Decathlon 20L Hiking Backpack",
        "price": 1999,
        "original_price": 3499,
        "discount": 43,
        "category": "sports",
        "subcategory": "outdoor",
        "rating": 4.5,
        "reviews": 34567,
        "image": "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=500",
        "badge": "43% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    
    # Toys & Games (ID: 91-100)
    {
        "id": 91,
        "name": "LEGO Star Wars Millennium Falcon",
        "price": 6999,
        "original_price": 9999,
        "discount": 30,
        "category": "toys",
        "subcategory": "construction",
        "rating": 4.9,
        "reviews": 23456,
        "image": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=500",
        "badge": "30% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 92,
        "name": "Hot Wheels 50 Car Pack",
        "price": 2999,
        "original_price": 4999,
        "discount": 40,
        "category": "toys",
        "subcategory": "diecast",
        "rating": 4.7,
        "reviews": 34567,
        "image": "https://images.unsplash.com/photo-1594787318286-7d8355f5c39c?w=500",
        "badge": "40% Off",
        "delivery": "₹40 Delivery",
        "prime": False,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 93,
        "name": "Barbie Dreamhouse Playset",
        "price": 8999,
        "original_price": 14999,
        "discount": 40,
        "category": "toys",
        "subcategory": "dolls",
        "rating": 4.8,
        "reviews": 12345,
        "image": "https://images.unsplash.com/photo-1594787318286-7d8355f5c39c?w=500",
        "badge": "40% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 94,
        "name": "Hasbro Monopoly Classic Board Game",
        "price": 699,
        "original_price": 1299,
        "discount": 46,
        "category": "toys",
        "subcategory": "board_games",
        "rating": 4.6,
        "reviews": 45678,
        "image": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=500",
        "badge": "46% Off",
        "delivery": "₹30 Delivery",
        "prime": False,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 95,
        "name": "Nerf N-Strike Elite Disruptor",
        "price": 1999,
        "original_price": 3499,
        "discount": 43,
        "category": "toys",
        "subcategory": "blasters",
        "rating": 4.5,
        "reviews": 23456,
        "image": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=500",
        "badge": "43% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 96,
        "name": "Rubik's Cube 3x3",
        "price": 299,
        "original_price": 599,
        "discount": 50,
        "category": "toys",
        "subcategory": "puzzles",
        "rating": 4.5,
        "reviews": 345678,
        "image": "https://images.unsplash.com/photo-1594787318286-7d8355f5c39c?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 97,
        "name": "Fisher-Price Baby Bouncer",
        "price": 3999,
        "original_price": 6999,
        "discount": 43,
        "category": "toys",
        "subcategory": "baby_toys",
        "rating": 4.6,
        "reviews": 12345,
        "image": "https://images.unsplash.com/photo-1594787318286-7d8355f5c39c?w=500",
        "badge": "43% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 98,
        "name": "Mattel Uno Card Game",
        "price": 149,
        "original_price": 299,
        "discount": 50,
        "category": "toys",
        "subcategory": "card_games",
        "rating": 4.7,
        "reviews": 234567,
        "image": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 99,
        "name": "Play-Doh 20 Can Set",
        "price": 999,
        "original_price": 1999,
        "discount": 50,
        "category": "toys",
        "subcategory": "creative",
        "rating": 4.6,
        "reviews": 34567,
        "image": "https://images.unsplash.com/photo-1594787318286-7d8355f5c39c?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    },
    {
        "id": 100,
        "name": "Funskool Scrabble Board Game",
        "price": 899,
        "original_price": 1799,
        "discount": 50,
        "category": "toys",
        "subcategory": "board_games",
        "rating": 4.7,
        "reviews": 23456,
        "image": "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=500",
        "badge": "50% Off",
        "delivery": "Free Delivery",
        "prime": True,
        "assured": True,
        "in_stock": True
    }
]

orders = []